import logging
import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def _score_class(score):
    if score >= 70:
        return 'class="high"'
    if score >= 40:
        return 'class="med"'
    return 'class="low"'


def _position_class(pos):
    if pos == 'Pursue Immediately':
        return 'class="pos-pursue"'
    if pos == 'Pursue with Consortium':
        return 'class="pos-consortium"'
    if pos == 'Monitor':
        return 'class="pos-monitor"'
    return 'class="pos-decline"'


def _build_html_table(analyses):
    rows_html = ''
    for a in analyses:
        title_raw = (a.get('title') or '(no title)')[:100]
        url = a.get('url') or ''
        title = f'<a href="{url}" target="_blank" style="color:#6366f1;text-decoration:none;font-weight:500">{title_raw}</a>' if url else title_raw
        score = a.get('score', 0)
        unit = a.get('relevant_unit') or '—'
        position = a.get('suggested_position') or 'Monitor'
        country = a.get('country') or a.get('geography') or '—'
        org = a.get('organization') or a.get('funding_organization') or '—'
        source = a.get('source') or '—'
        summary = (a.get('executive_summary') or '')[:200]

        rows_html += f'''
        <tr>
          <td {_score_class(score)}>{score}</td>
          <td {_position_class(position)}>{position}</td>
          <td>{title}</td>
          <td>{org}</td>
          <td>{country}</td>
          <td>{unit}</td>
          <td>{source}</td>
          <td style="font-size:12px;color:#666;max-width:300px">{summary}</td>
        </tr>'''

    return f'''<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f4f4f9;padding:20px}}
    .container{{max-width:800px;margin:0 auto}}
    h1{{font-size:22px;color:#1a1a2e;margin-bottom:4px}}
    p{{color:#6b6b8a;font-size:14px;margin-bottom:20px}}
    table{{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.06)}}
    th{{text-align:left;padding:10px 14px;font-size:11px;font-weight:600;color:#6b6b8a;background:#f0f0f6;text-transform:uppercase;letter-spacing:.3px;border-bottom:1px solid #dcdce6}}
    td{{padding:10px 14px;font-size:13px;color:#1a1a2e;border-bottom:1px solid #dcdce6}}
    tr:last-child td{{border-bottom:none}}
    .high{{font-weight:700;color:#10b981}}
    .med{{font-weight:700;color:#f59e0b}}
    .low{{font-weight:700;color:#ef4444}}
    .pos-pursue{{font-weight:600;color:#10b981}}
    .pos-consortium{{font-weight:600;color:#6366f1}}
    .pos-monitor{{font-weight:600;color:#f59e0b}}
    .pos-decline{{font-weight:600;color:#ef4444}}
    .footer{{margin-top:16px;font-size:12px;color:#6b6b8a;text-align:center}}
    .summary{{font-size:14px;color:#1a1a2e;margin-bottom:16px}}
    .summary strong{{color:#6366f1}}
  </style>
</head>
<body>
  <div class="container">
    <h1>Nextier Opportunity Finder — Opportunity Report</h1>
    <p>AI-ranked procurement opportunities sorted by score</p>
    <div class="summary">
      Found <strong>{len(analyses)}</strong> scored opportunities.
      <span style="color:#10b981">● {sum(1 for a in analyses if a.get('score', 0) >= 70)} high</span>
      <span style="color:#f59e0b">● {sum(1 for a in analyses if 40 <= a.get('score', 0) < 70)} medium</span>
      <span style="color:#ef4444">● {sum(1 for a in analyses if a.get('score', 0) < 40)} low</span>
    </div>
    <table>
      <thead>
        <tr>
          <th>Score</th>
          <th>Position</th>
          <th>Title</th>
          <th>Organization</th>
          <th>Country</th>
          <th>Unit</th>
          <th>Source</th>
          <th>Summary</th>
        </tr>
      </thead>
      <tbody>
        {rows_html}
      </tbody>
    </table>
    <div class="footer">
      Generated by Nextier Opportunity Finder AI — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
    </div>
  </div>
</body>
</html>'''


def send_analysis_email(to_addrs, analyses, smtp_host=None, smtp_port=None, smtp_user=None, smtp_pass=None, email_from=None, excel_bytes=None, excel_filename=None):
    if not to_addrs:
        logger.warning('[Email] No recipients — skipping')
        return {'results': [], 'sent': 0, 'failed': 0, 'error': 'No recipients'}

    host = smtp_host or os.getenv('SMTP_HOST', 'smtp.gmail.com')
    port = smtp_port or int(os.getenv('SMTP_PORT', 587))
    user = smtp_user or os.getenv('SMTP_USER', '')
    pwd = smtp_pass or os.getenv('SMTP_PASS', '')
    frm = email_from or os.getenv('EMAIL_FROM', '')

    if not user or not pwd:
        logger.warning('[Email] SMTP not configured — skipping')
        return {'results': [], 'sent': 0, 'failed': 0, 'error': 'SMTP not configured'}

    if isinstance(to_addrs, str):
        to_addrs = [a.strip() for a in to_addrs.split(',') if a.strip()]

    analyses_sorted = sorted(analyses, key=lambda a: a.get('score', 0), reverse=True)
    html = _build_html_table(analyses_sorted)

    if excel_filename is None:
        excel_filename = f'opportunities_{datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")}.xlsx'

    excel_data = excel_bytes.read() if excel_bytes is not None else None

    results = []
    try:
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.starttls()
            server.login(user, pwd)
            for addr in to_addrs:
                msg = MIMEMultipart('mixed')
                msg['Subject'] = f'Nextier Opportunity Finder Report — {len(analyses)} opportunities scored'
                msg['From'] = frm
                msg['To'] = addr

                alt = MIMEMultipart('alternative')
                alt.attach(MIMEText(html, 'html'))
                msg.attach(alt)

                if excel_data is not None:
                    part = MIMEBase('application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                    part.set_payload(excel_data)
                    encoders.encode_base64(part)
                    part.add_header('Content-Disposition', f'attachment; filename="{excel_filename}"')
                    msg.attach(part)

                try:
                    server.sendmail(frm, [addr], msg.as_string())
                    results.append({'address': addr, 'status': 'sent', 'error': None})
                    logger.info(f'[Email] Sent to {addr}')
                except Exception as e:
                    results.append({'address': addr, 'status': 'failed', 'error': str(e)})
                    logger.warning(f'[Email] Failed to send to {addr}: {e}')
    except Exception as e:
        # SMTP connection/authentication failed — mark all as failed
        results = [{'address': a, 'status': 'failed', 'error': str(e)} for a in to_addrs]
        logger.exception('[Email] SMTP connection failed')

    sent = sum(1 for r in results if r['status'] == 'sent')
    failed = sum(1 for r in results if r['status'] == 'failed')
    logger.info(f'[Email] Done — {sent} sent, {failed} failed')
    return {'results': results, 'sent': sent, 'failed': failed, 'error': None}
